# -*- coding: utf-8 -*-
"""Polyp_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1JoK7jbDemPWMMyamMtLq3r3CgObH16
"""

!wget https://datasets.simula.no/downloads/kvasir-seg.zip

!unzip kvasir-seg.zip

import os
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
import timm

# ---- Dataset ----
class KvasirSegDataset(Dataset):
    def __init__(self, images_dir, masks_dir, transform=None, mask_transform=None, mask_extension='.png'):
        self.images_dir = images_dir
        self.masks_dir = masks_dir
        self.transform = transform
        self.mask_transform = mask_transform
        self.mask_extension = mask_extension
        self.images = sorted([f for f in os.listdir(images_dir) if f.lower().endswith(('.jpg','.jpeg','.png'))])

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_name = self.images[idx]
        img_path = os.path.join(self.images_dir, img_name)
        base_name = os.path.splitext(img_name)[0]
        mask_name = base_name + self.mask_extension
        mask_path = os.path.join(self.masks_dir, mask_name)

        image = Image.open(img_path).convert("RGB")
        try:
            mask = Image.open(mask_path).convert("L")
        except FileNotFoundError:
            raise FileNotFoundError(f"Mask not found: {mask_path}")

        if self.transform:
            image = self.transform(image)
        if self.mask_transform:
            mask = self.mask_transform(mask)
        else:
            mask = T.ToTensor()(mask)
        mask = (mask > 0).float()  # Binarize
        return image, mask

# ---- Model Blocks ----
class MDCB(nn.Module):
    def __init__(self, in_ch, out_ch, dilations=[1, 2, 4]):
        super().__init__()
        self.convs = nn.ModuleList([
            nn.Conv2d(in_ch, out_ch, kernel_size=3, padding=d, dilation=d)
            for d in dilations
        ])
        self.relu = nn.ReLU(inplace=True)
        self.fuse = nn.Conv2d(len(dilations)*out_ch, out_ch, kernel_size=1)

    def forward(self, x):
        features = [conv(x) for conv in self.convs]
        x = torch.cat(features, dim=1)
        x = self.fuse(x)
        return self.relu(x)

class MFAB(nn.Module):
    def __init__(self, in_chs, out_ch):
        super().__init__()
        self.conv = nn.Conv2d(sum(in_chs), out_ch, kernel_size=1)

    def forward(self, *features):
        target_size = features[0].shape[2:]
        resized_features = [features[0]]
        for i in range(1, len(features)):
            resized = F.interpolate(features[i], size=target_size, mode='bicubic', align_corners=False)
            resized_features.append(resized)
        x = torch.cat(resized_features, dim=1)
        return self.conv(x)

# ---- SwinE-Net Model ----
class SwinENet(nn.Module):
    def __init__(self, num_classes=1,
                 swin_backbone='swin_base_patch4_window7_224',
                 effnet_backbone='efficientnet_b3'):
        super().__init__()
        # Swin Transformer backbone
        self.swin = timm.create_model(swin_backbone, pretrained=True, features_only=True)
        swin_channels = self.swin.feature_info.channels()
        # EfficientNet backbone
        self.effnet = timm.create_model(effnet_backbone, pretrained=True, features_only=True)
        effnet_channels = self.effnet.feature_info.channels()

        # Use only as many stages as both have
        num_stages = min(len(swin_channels), len(effnet_channels))
        swin_channels = swin_channels[:num_stages]
        effnet_channels = effnet_channels[:num_stages]
        self.num_stages = num_stages

        # Fusion and MDCB per stage
        fused_channels = [s+e for s, e in zip(swin_channels, effnet_channels)]
        self.mdcb = nn.ModuleList([
            MDCB(fused_ch, fused_ch) for fused_ch in fused_channels
        ])
        # Decoder
        decoder_in_ch = fused_channels[-1]
        self.decoder = nn.ModuleList([
            nn.ConvTranspose2d(decoder_in_ch, 256, 2, stride=2),
            nn.ConvTranspose2d(256, 128, 2, stride=2),
            nn.ConvTranspose2d(128, 64, 2, stride=2)
        ])
        # MFAB for skip connections (use first three stages)
        self.mfab = MFAB([fused_channels[0], fused_channels[1], fused_channels[2]], 64)
        self.final_conv = nn.Conv2d(64, num_classes, 1)

    def forward(self, x):
        swin_feats = self.swin(x)
        effnet_feats = self.effnet(x)

        # Permute if necessary (adjusting for timm feature output format)
        # Ensure features are in [B, C, H, W] format
        swin_feats_processed = []
        for f, ch in zip(swin_feats, self.swin.feature_info.channels()[:self.num_stages]):
             # Check if feature is from a layer that might output in [B, H*W, C] format
            if f.ndim == 3: # Assuming [B, H*W, C]
                B, HW, C = f.shape
                H = W = int(HW**0.5) # Assuming square features
                swin_feats_processed.append(f.view(B, H, W, C).permute(0, 3, 1, 2)) # Reshape and permute to [B, C, H, W]
            elif f.ndim == 4: # Assuming [B, C, H, W] or [B, H, W, C]
                 # Check if channel dim seems to be the last one and should be second
                if f.shape[-1] == ch and f.shape[1] != ch: # Likely [B, H, W, C], permute to [B, C, H, W]
                    swin_feats_processed.append(f.permute(0, 3, 1, 2))
                else: # Assume [B, C, H, W] already
                    swin_feats_processed.append(f)
            else:
                 # Handle other dimensions if necessary, or raise an error
                 raise ValueError(f"Unexpected Swin feature tensor shape: {f.shape}")

        effnet_feats_processed = []
        for f, ch in zip(effnet_feats, self.effnet.feature_info.channels()[:self.num_stages]):
             # EfficientNet features from timm usually come in [B, C, H, W]
            if f.ndim == 4: # Assuming [B, C, H, W] or [B, H, W, C]
                 # Check if channel dim seems to be the last one and should be second
                if f.shape[-1] == ch and f.shape[1] != ch: # Likely [B, H, W, C], permute to [B, C, H, W]
                    effnet_feats_processed.append(f.permute(0, 3, 1, 2))
                else: # Assume [B, C, H, W] already
                    effnet_feats_processed.append(f)
            else:
                 # Handle other dimensions if necessary, or raise an error
                 raise ValueError(f"Unexpected EfficientNet feature tensor shape: {f.shape}")


        # Fuse features at each scale after potentially resizing EfficientNet features
        fused_feats = []
        for swin_f, effnet_f in zip(swin_feats_processed, effnet_feats_processed):
            # Check if spatial dimensions match
            if swin_f.shape[2:] != effnet_f.shape[2:]:
                # If not, resize the EfficientNet feature to match the Swin feature size
                # Using 'bilinear' or 'nearest' for resizing feature maps is common.
                # 'bicubic' might be too slow or introduce artifacts for features.
                # Let's choose bilinear as a general option.
                target_size = swin_f.shape[2:]
                effnet_f_resized = F.interpolate(effnet_f, size=target_size, mode='bilinear', align_corners=False)
                fused_feats.append(torch.cat([swin_f, effnet_f_resized], dim=1))
            else:
                # If dimensions match, just concatenate
                fused_feats.append(torch.cat([swin_f, effnet_f], dim=1))

        # MDCB enhancement
        feats = [mdcb(f) for mdcb, f in zip(self.mdcb, fused_feats)]

        # Decoder path
        x = feats[-1]
        for dec in self.decoder:
            x = dec(x)

        # MFAB aggregation
        # Check if mfab_inputs have matching spatial dimensions before passing to MFAB
        # MFAB expects features[0] as the target size.
        # Let's resize features[1] and features[2] to match features[0].shape[2:]
        mfab_inputs = [feats[0]] # feats[0] is the first stage feature
        # Resize feats[1] to match feats[0]
        if feats[1].shape[2:] != feats[0].shape[2:]:
             resized_feat1 = F.interpolate(feats[1], size=feats[0].shape[2:], mode='bilinear', align_corners=False)
             mfab_inputs.append(resized_feat1)
        else:
             mfab_inputs.append(feats[1])
        # Resize feats[2] to match feats[0]
        if feats[2].shape[2:] != feats[0].shape[2:]:
             resized_feat2 = F.interpolate(feats[2], size=feats[0].shape[2:], mode='bilinear', align_corners=False)
             mfab_inputs.append(resized_feat2)
        else:
             mfab_inputs.append(feats[2])

        # Pass the potentially resized features to MFAB
        x = self.mfab(*mfab_inputs)


        x = self.final_conv(x)

        # Upsample to input size (224x224)
        if x.shape[2:] != (224, 224):
            x = F.interpolate(x, size=(224, 224), mode='bilinear', align_corners=False)

        return x

# Transforms
image_transform = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor(),
    T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
mask_transform = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor()
])

# Dataset/Dataloader
dataset = KvasirSegDataset(
    images_dir='/content/Kvasir-SEG/images',
    masks_dir='/content/Kvasir-SEG/masks',
    transform=image_transform,
    mask_transform=mask_transform,
    mask_extension='.jpg'  # or whatever your mask files use
)
loader = DataLoader(dataset, batch_size=8, shuffle=True)

# Model instantiation
model = SwinENet(num_classes=1)
# Example forward pass
for images, masks in loader:
    preds = model(images)
    print(preds.shape)  # Should be [B, 1, 224, 224]
    break

import os
from PIL import Image
import torch
from torch.utils.data import Dataset
import torchvision.transforms as T

class KvasirSegDataset(Dataset):
    def __init__(self, images_dir, masks_dir, transform=None, mask_transform=None):
        self.images_dir = images_dir
        self.masks_dir = masks_dir
        self.transform = transform
        self.mask_transform = mask_transform
        self.images = sorted(os.listdir(images_dir))
        self.mask_extension = '.jpg'  # mask file extension


    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_name = self.images[idx]
        img_path = os.path.join(self.images_dir, img_name)
        base_name = os.path.splitext(img_name)[0] # filename without ext
        mask_name = base_name + self.mask_extension
        mask_path = os.path.join(self.masks_dir, mask_name)

        image = Image.open(img_path).convert("RGB")
        mask = Image.open(mask_path).convert("L")  # grayscale mask

        if self.transform:
            image = self.transform(image)
        if self.mask_transform:
            mask = self.mask_transform(mask)
        else:
            mask = T.ToTensor()(mask)
            # For binary segmentation, ensure mask is 0/1
            mask = (mask > 0).float()
        return image, mask

from torch.utils.data import DataLoader
import torchvision.transforms as T

image_transform = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor(),
    T.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225])
])

mask_transform = T.Compose([
    T.Resize((224,224)),
    T.ToTensor()
])

dataset = KvasirSegDataset(
    images_dir='/content/Kvasir-SEG/images',
    masks_dir='/content/Kvasir-SEG/masks',
    transform=image_transform,
    mask_transform=mask_transform
)

loader = DataLoader(dataset, batch_size=8, shuffle=True)

import torch

model = SwinENet(num_classes=1)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = torch.nn.BCEWithLogitsLoss()  # or Dice Loss

for images, masks in loader:
    preds = model(images)
    loss = criterion(preds, masks)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# Save the trained model
model_save_path = '/content/swinenet_kvasir_seg.pth'
torch.save(model.state_dict(), model_save_path)
print(f"Model saved to {model_save_path}")

# --- Code to save prediction masks for all examples ---
model.eval() # Set model to evaluation mode
output_masks_dir = '/content/predicted_masks'
os.makedirs(output_masks_dir, exist_ok=True) # Create directory if it doesn't exist

# Removed num_examples_to_save and related batch calculation
# The code will now iterate through all batches in the loader

# Initialize a counter for the total number of masks saved
total_saved_count = 0

with torch.no_grad(): # Disable gradient calculation for inference
    # Iterate through ALL batches in the loader
    for i, (images, masks) in enumerate(loader):
        preds = model(images)

        # Apply sigmoid and threshold to get binary masks (assuming BCEWithLogitsLoss was used)
        predicted_masks = torch.sigmoid(preds) > 0.5

        # Iterate over each example in the current batch
        for j in range(images.size(0)):
            # Convert the predicted mask to a PIL Image
            # Squeeze to remove batch and channel dimensions, convert to uint8
            mask_img = predicted_masks[j].squeeze(0).byte().cpu() * 255 # Convert to 0-255 for saving
            mask_pil = Image.fromarray(mask_img.numpy(), mode='L') # 'L' for grayscale

            # Save the predicted mask using the global counter for filename index
            mask_filename = f"predicted_mask_{total_saved_count:04d}.png" # e.g., predicted_mask_0000.png
            mask_filepath = os.path.join(output_masks_dir, mask_filename)
            mask_pil.save(mask_filepath)
            print(f"Saved predicted mask to {mask_filepath}")

            # Increment the total saved count
            total_saved_count += 1

print(f"Finished saving {total_saved_count} predicted masks.")

!pip install --upgrade torchmetrics

# Install torchmetrics if not already installed, and upgrade to ensure latest version
# Re-run this command to ensure torchmetrics is up-to-date


import torch
import torchmetrics
# Import Dice specifically from torchmetrics
from torchmetrics.segmentation import DiceScore # Import Dice directly from torchmetrics
import os
from PIL import Image
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
import torch.nn.functional as F
import timm
import torch.nn as nn
import torchmetrics # Keep this if you use torchmetrics.JaccardIndex etc. directly

# Re-define model and classes if running in a fresh environment, otherwise skip
# Assuming the model definition, dataset, and loader are already defined as before

# Load the trained model state dictionary
# The model definition and loader instantiation should be run *before* this cell
# if you are restarting the notebook or running cells out of order.
# For a sequential run, they are already defined in previous cells.
try:
    model # Check if model exists
except NameError:
    # If model is not defined (e.g., running this cell first), instantiate it
    print("Model not found, instantiating SwinENet.")
    # Assuming SwinENet class is defined in a previous cell or imported
    # If it's not defined yet, uncomment and potentially copy its definition here
    # from your model definition cell:
    # class SwinENet(...): ...
    model = SwinENet(num_classes=1)

model_save_path = '/content/swinenet_kvasir_seg.pth'
if os.path.exists(model_save_path):
    try:
        # Ensure the model is on the correct device before loading state_dict if using GPU
        # device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        # model.to(device)
        model.load_state_dict(torch.load(model_save_path))
        print(f"Loaded model from {model_save_path}")
    except RuntimeError as e:
        print(f"Error loading model state_dict: {e}")
        print("This might happen if the model architecture definition has changed or device mismatch.")
        # Handle error, e.g., continue without loading or raise the exception
        # raise e # Uncomment to stop execution on load error
else:
    print(f"Model state dict not found at {model_save_path}. Cannot evaluate.")
    # Decide how to proceed: train a new model, skip evaluation, etc.
    # For this example, we'll print a warning and continue (model will be untrained)

model.eval() # Set model to evaluation mode

# Define the metrics to calculate
# Use 'binary' for binary segmentation (1 class + background)
# torchmetrics.Dice is the correct class name for the binary Dice metric in recent versions
# The error "AttributeError: module 'torchmetrics' has no attribute 'Dice'"
# strongly suggests an issue with the torchmetrics installation or version.
# Re-running the pip install command and ensuring the kernel is refreshed
# is the primary fix. The line below is correct for recent torchmetrics versions.
metric_iou = torchmetrics.JaccardIndex(task="binary")
# The problematic line, now corrected:
metric_dice = DiceScore(num_classes=2) # Now imported directly from torchmetrics
metric_accuracy = torchmetrics.Accuracy(task="binary")

print("\nCalculating evaluation metrics...")

# Disable gradient calculation for inference
with torch.no_grad():
    # Iterate through the data loader
    # Ensure the loader is instantiated from a previous cell
    try:
        loader # Check if loader exists
    except NameError:
        print("DataLoader not found. Please run the cell that defines the dataset and loader.")
        # You might want to re-create the loader here if necessary
        # Example (assuming dataset and transforms are defined):
        # dataset = KvasirSegDataset(...) # Make sure KvasirSegDataset is defined/imported
        # image_transform = T.Compose([...]) # Make sure transforms are defined
        # mask_transform = T.Compose([...]) # Make sure transforms are defined
        # loader = DataLoader(dataset, batch_size=8, shuffle=True)
        # If you cannot re-create, you might need to stop execution
        exit() # Stop execution if loader is critical

    for i, (images, masks) in enumerate(loader):
        # Assuming loader outputs images and ground truth masks

        # Move data to the same device as the model (optional, but good practice if using GPU)
        # device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        # images = images.to(device)
        # masks = masks.to(device)
        # model.to(device) # Ensure model is on the device
        # # Metrics also need to be on the same device
        # metric_iou.to(device)
        # metric_dice.to(device)
        # metric_accuracy.to(device)

        preds = model(images)

        # Apply sigmoid to predictions and threshold to get binary masks (0 or 1)
        # Ensure predictions and masks are on the same device and dtype for metric calculation
        predicted_masks_binary = (torch.sigmoid(preds) > 0.5).int() # Convert boolean to integer (0 or 1)

        # Update metrics with the current batch
        # Predicted masks should be int (0 or 1) and ground truth masks float or int
        # JaccardIndex and Dice expect inputs to be the same size
        # Ensure ground truth mask is also int (0 or 1) if needed by metric (ToTensor already makes it float)
        # Let's ensure the target is also binary int for clarity
        masks_binary = (masks > 0).int()

        metric_iou.update(predicted_masks_binary, masks_binary)
        metric_dice.update(predicted_masks_binary, masks_binary)
        metric_accuracy.update(predicted_masks_binary, masks_binary)

# Compute the final metric values
final_iou = metric_iou.compute()
final_dice = metric_dice.compute()
final_accuracy = metric_accuracy.compute()

# Print the metrics
print(f"Evaluation Metrics over the entire dataset:")
print(f"  Mean IoU: {final_iou.item():.4f}")
print(f"  Mean Dice: {final_dice.item():.4f}")
print(f"  Overall Accuracy: {final_accuracy.item():.4f}")

# Reset metrics for potential future use (optional)
metric_iou.reset()
metric_dice.reset()
metric_accuracy.reset()

!zip -r /content/predicted_masks.zip /content/predicted_masks

from google.colab import files
files.download("/content/predicted_masks")