# -*- coding: utf-8 -*-
"""Polyp_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1JoK7jbDemPWMMyamMtLq3r3CgObH16
"""

!wget https://datasets.simula.no/downloads/kvasir-seg.zip

!unzip kvasir-seg.zip

!pip install --upgrade torchmetrics

import os
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
import timm

# 1. Dataset
class KvasirSegDataset(Dataset):
    def __init__(self, images_dir, masks_dir, transform=None, mask_transform=None, mask_extension='.jpg'):
        self.images_dir = images_dir
        self.masks_dir = masks_dir
        self.transform = transform
        self.mask_transform = mask_transform
        self.mask_extension = mask_extension
        self.images = sorted([f for f in os.listdir(images_dir) if f.lower().endswith(('.jpg','.jpeg','.png'))])

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_name = self.images[idx]
        img_path = os.path.join(self.images_dir, img_name)
        base_name = os.path.splitext(img_name)[0]
        mask_name = base_name + self.mask_extension
        mask_path = os.path.join(self.masks_dir, mask_name)

        image = Image.open(img_path).convert("RGB")
        try:
            mask = Image.open(mask_path).convert("L")
        except FileNotFoundError:
            raise FileNotFoundError(f"Mask not found: {mask_path}")

        if self.transform:
            image = self.transform(image)
        if self.mask_transform:
            mask = self.mask_transform(mask)
        else:
            mask = T.ToTensor()(mask)
        mask = (mask > 0).float()  # Binarize
        return image, mask

# 2. Model Blocks
class MDCB(nn.Module):
    def __init__(self, in_ch, out_ch, dilations=[1, 2, 4]):
        super().__init__()
        self.convs = nn.ModuleList([
            nn.Conv2d(in_ch, out_ch, kernel_size=3, padding=d, dilation=d)
            for d in dilations
        ])
        self.relu = nn.ReLU(inplace=True)
        self.fuse = nn.Conv2d(len(dilations)*out_ch, out_ch, kernel_size=1)

    def forward(self, x):
        features = [conv(x) for conv in self.convs]
        x = torch.cat(features, dim=1)
        x = self.fuse(x)
        return self.relu(x)

class MFAB(nn.Module):
    def __init__(self, in_chs, out_ch):
        super().__init__()
        self.conv = nn.Conv2d(sum(in_chs), out_ch, kernel_size=1)

    def forward(self, *features):
        target_size = features[0].shape[2:]
        resized_features = [features[0]]
        for i in range(1, len(features)):
            resized = F.interpolate(features[i], size=target_size, mode='bicubic', align_corners=False)
            resized_features.append(resized)
        x = torch.cat(resized_features, dim=1)
        return self.conv(x)

# 3. SwinE-Net Model
class SwinENet(nn.Module):
    def __init__(self, num_classes=1,
                 swin_backbone='swin_base_patch4_window7_224',
                 effnet_backbone='efficientnet_b3'):
        super().__init__()
        # Swin Transformer backbone
        self.swin = timm.create_model(swin_backbone, pretrained=True, features_only=True)
        swin_channels = self.swin.feature_info.channels()
        # EfficientNet backbone
        self.effnet = timm.create_model(effnet_backbone, pretrained=True, features_only=True)
        effnet_channels = self.effnet.feature_info.channels()

        # Use only as many stages as both have
        num_stages = min(len(swin_channels), len(effnet_channels))
        swin_channels = swin_channels[:num_stages]
        effnet_channels = effnet_channels[:num_stages]
        self.num_stages = num_stages

        # Fusion and MDCB per stage
        fused_channels = [s+e for s, e in zip(swin_channels, effnet_channels)]
        self.mdcb = nn.ModuleList([
            MDCB(fused_ch, fused_ch) for fused_ch in fused_channels
        ])
        # Decoder
        decoder_in_ch = fused_channels[-1]
        self.decoder = nn.ModuleList([
            nn.ConvTranspose2d(decoder_in_ch, 256, 2, stride=2),
            nn.ConvTranspose2d(256, 128, 2, stride=2),
            nn.ConvTranspose2d(128, 64, 2, stride=2)
        ])
        # MFAB for skip connections (use first three stages)
        self.mfab = MFAB([fused_channels[0], fused_channels[1], fused_channels[2]], 64)
        self.final_conv = nn.Conv2d(64, num_classes, 1)

    def forward(self, x):
        swin_feats = self.swin(x)
        effnet_feats = self.effnet(x)

        # Permute if necessary (adjusting for timm feature output format)
        # Ensure features are in [B, C, H, W] format
        swin_feats_processed = []
        for f, ch in zip(swin_feats, self.swin.feature_info.channels()[:self.num_stages]):
             # Check if feature is from a layer that might output in [B, H*W, C] format
            if f.ndim == 3: # Assuming [B, H*W, C]
                B, HW, C = f.shape
                H = W = int(HW**0.5) # Assuming square features
                swin_feats_processed.append(f.view(B, H, W, C).permute(0, 3, 1, 2)) # Reshape and permute to [B, C, H, W]
            elif f.ndim == 4: # Assuming [B, C, H, W] or [B, H, W, C]
                 # Check if channel dim seems to be the last one and should be second
                if f.shape[-1] == ch and f.shape[1] != ch: # Likely [B, H, W, C], permute to [B, C, H, W]
                    swin_feats_processed.append(f.permute(0, 3, 1, 2))
                else: # Assume [B, C, H, W] already
                    swin_feats_processed.append(f)
            else:
                 # Handle other dimensions if necessary, or raise an error
                 raise ValueError(f"Unexpected Swin feature tensor shape: {f.shape}")

        effnet_feats_processed = []
        for f, ch in zip(effnet_feats, self.effnet.feature_info.channels()[:self.num_stages]):
             # EfficientNet features from timm usually come in [B, C, H, W]
            if f.ndim == 4: # Assuming [B, C, H, W] or [B, H, W, C]
                 # Check if channel dim seems to be the last one and should be second
                if f.shape[-1] == ch and f.shape[1] != ch: # Likely [B, H, W, C], permute to [B, C, H, W]
                    effnet_feats_processed.append(f.permute(0, 3, 1, 2))
                else: # Assume [B, C, H, W] already
                    effnet_feats_processed.append(f)
            else:
                 # Handle other dimensions if necessary, or raise an error
                 raise ValueError(f"Unexpected EfficientNet feature tensor shape: {f.shape}")


        # Fuse features at each scale after potentially resizing EfficientNet features
        fused_feats = []
        for swin_f, effnet_f in zip(swin_feats_processed, effnet_feats_processed):
            # Check if spatial dimensions match
            if swin_f.shape[2:] != effnet_f.shape[2:]:
                # If not, resize the EfficientNet feature to match the Swin feature size
                # Using 'bilinear' or 'nearest' for resizing feature maps is common.
                # 'bicubic' might be too slow or introduce artifacts for features.
                # Let's choose bilinear as a general option.
                target_size = swin_f.shape[2:]
                effnet_f_resized = F.interpolate(effnet_f, size=target_size, mode='bilinear', align_corners=False)
                fused_feats.append(torch.cat([swin_f, effnet_f_resized], dim=1))
            else:
                # If dimensions match, just concatenate
                fused_feats.append(torch.cat([swin_f, effnet_f], dim=1))

        # MDCB enhancement
        feats = [mdcb(f) for mdcb, f in zip(self.mdcb, fused_feats)]

        # Decoder path
        x = feats[-1]
        for dec in self.decoder:
            x = dec(x)

        # MFAB aggregation
        # Check if mfab_inputs have matching spatial dimensions before passing to MFAB
        # MFAB expects features[0] as the target size.
        # Let's resize features[1] and features[2] to match features[0].shape[2:]
        mfab_inputs = [feats[0]] # feats[0] is the first stage feature
        # Resize feats[1] to match feats[0]
        if feats[1].shape[2:] != feats[0].shape[2:]:
             resized_feat1 = F.interpolate(feats[1], size=feats[0].shape[2:], mode='bilinear', align_corners=False)
             mfab_inputs.append(resized_feat1)
        else:
             mfab_inputs.append(feats[1])
        # Resize feats[2] to match feats[0]
        if feats[2].shape[2:] != feats[0].shape[2:]:
             resized_feat2 = F.interpolate(feats[2], size=feats[0].shape[2:], mode='bilinear', align_corners=False)
             mfab_inputs.append(resized_feat2)
        else:
             mfab_inputs.append(feats[2])

        # Pass the potentially resized features to MFAB
        x = self.mfab(*mfab_inputs)


        x = self.final_conv(x)

        # Upsample to input size (224x224)
        if x.shape[2:] != (224, 224):
            x = F.interpolate(x, size=(224, 224), mode='bilinear', align_corners=False)

        return x

# 4. Transforms
image_transform = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor(),
    T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
mask_transform = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor()
])

# 5. Dataset/Dataloader
dataset = KvasirSegDataset(
    images_dir='/content/Kvasir-SEG/images',
    masks_dir='/content/Kvasir-SEG/masks',
    transform=image_transform,
    mask_transform=mask_transform,
    mask_extension='.jpg'
)
loader = DataLoader(dataset, batch_size=8, shuffle=True)

# 6. Model instantiation
model = SwinENet(num_classes=1)
# Move the model to the GPU
model.cuda()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = torch.nn.BCEWithLogitsLoss()

# 7. Training model

num_epochs = 6 # Number of training epochs

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    for i, (images, masks) in enumerate(loader):
        images = images.cuda()
        masks = masks.cuda()

        optimizer.zero_grad()
        preds = model(images)

        loss = criterion(preds, masks)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)

    epoch_loss = running_loss / len(dataset)
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}")

# 8. Saving the model
model_save_path = '/content/swinenet_kvasir_seg.pth'
torch.save(model.state_dict(), model_save_path)
print(f"Model saved to {model_save_path}")

# 9. Save prediction masks
model.eval()
output_masks_dir = '/content/predicted_masks'

os.makedirs(output_masks_dir, exist_ok=True)

total_saved_count = 0

with torch.no_grad():
    for i, (images, masks) in enumerate(loader):
        # Move images to the GPU before passing to the model
        images = images.cuda() # Add this line
        preds = model(images)

        # Applying sigmoid and threshold to get binary masks
        predicted_masks = torch.sigmoid(preds) > 0.5

        for j in range(images.size(0)):
            # Remove batch and channel dimensions
            mask_img = predicted_masks[j].squeeze(0).byte().cpu() * 255
            mask_pil = Image.fromarray(mask_img.numpy(), mode='L')

            # Saving the predicted mask using the global counter for filename index
            mask_filename = f"predicted_mask_{total_saved_count:04d}.jpg"
            mask_filepath = os.path.join(output_masks_dir, mask_filename)
            mask_pil.save(mask_filepath)
            print(f"Saved predicted mask to {mask_filepath}")

            # Increment the total saved count
            total_saved_count += 1

print(f"Finished saving {total_saved_count} predicted masks.")

# 10. Printing predictions

import torchmetrics
from torchmetrics.segmentation import DiceScore

try:
    model
except NameError:
    print("Model not found, instantiating SwinENet.")
    model = SwinENet(num_classes=1)

model_save_path = '/content/swinenet_kvasir_seg.pth'
if os.path.exists(model_save_path):
    try:
        model.load_state_dict(torch.load(model_save_path))
        print(f"Loaded model from {model_save_path}")
    except RuntimeError as e:
        print(f"Error loading model state_dict: {e}")
        print("This might happen if the model architecture definition has changed or device mismatch.")
else:
    print(f"Model state dict not found at {model_save_path}. Cannot evaluate.")

# Move the model to the GPU before evaluation
model.cuda() # Ensure the model is on the GPU for evaluation too

model.eval()

# Move metric objects to the GPU
metric_iou = torchmetrics.JaccardIndex(task="binary").cuda()
metric_dice = DiceScore(num_classes=2).cuda()
metric_accuracy = torchmetrics.Accuracy(task="binary").cuda()


print("\nCalculating evaluation metrics...")

with torch.no_grad():
    try:
        loader
    except NameError:
        print("DataLoader not found. Please run the cell that defines the dataset and loader.")
        exit()

    for i, (images, masks) in enumerate(loader):

        # Move images to the GPU before passing to the model
        images = images.cuda() # Moved this line up
        masks = masks.cuda()   # Also move masks to GPU for metrics if needed

        # Debugging 1.100
        # The debugging prints were causing issues because 'preds' was not defined yet
        # before the model call. Let's get the predictions first.
        preds = model(images)

        print(f"Batch {i}:")
        print(f"  Raw predictions shape: {preds.shape}")
        print(f"  Raw predictions min: {preds.min().item()}, max: {preds.max().item()}")
        sigmoid_preds = torch.sigmoid(preds)
        print(f"  Sigmoid predictions min: {sigmoid_preds.min().item()}, max: {sigmoid_preds.max().item()}")
        # End Debugging 1.100

        predicted_masks_binary = (torch.sigmoid(preds) > 0.5).int()  # Convert to binary masks
        masks_binary = (masks > 0).int()

        # Pass GPU tensors to the GPU metric objects
        metric_iou.update(predicted_masks_binary, masks_binary)
        metric_dice.update(predicted_masks_binary, masks_binary)
        metric_accuracy.update(predicted_masks_binary, masks_binary)

# Compute the final metric values
final_iou = metric_iou.compute()
final_dice = metric_dice.compute()
final_accuracy = metric_accuracy.compute()

print(f"Evaluation Metrics over the entire dataset:")
print(f"  Mean IoU: {final_iou.item():.4f}")
print(f"  Mean Dice: {final_dice.item():.4f}")
print(f"  Overall Accuracy: {final_accuracy.item():.4f}")

metric_iou.reset()
metric_dice.reset()
metric_accuracy.reset()

!zip -r /content/predicted_masks.zip /content/predicted_masks

from google.colab import files
files.download("/content/predicted_masks.zip")