# -*- coding: utf-8 -*-
"""Polyp_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLcmm81vQ2eZzD18liIIKVf3np-srL8O
"""

!wget https://datasets.simula.no/downloads/kvasir-seg.zip

!unzip kvasir-seg.zip

!pip install -q kaggle

from google.colab import files
files.upload()

# Step 1: Create the Kaggle folder if it doesn't exist
!mkdir -p ~/.kaggle

# Step 2: Move the uploaded kaggle.json to the correct location
!mv kaggle.json ~/.kaggle/

!kaggle datasets download -d wcy111/cvc-clinicdb
!unzip -q cvc-clinicdb.zip

!pip install --upgrade torchmetrics

import cv2
import os

def convert_with_cv2(folder):
    for filename in os.listdir(folder):
        if filename.endswith((".tif", ".tiff")):
            path = os.path.join(folder, filename)
            img = cv2.imread(path, cv2.IMREAD_UNCHANGED)  # Load image

            if img is None:
                print(f"Warning: OpenCV couldn't read {filename}")
                continue

            # Optional: Normalize 16-bit to 8-bit if needed
            if img.dtype == 'uint16':
                img = (img / 256).astype('uint8')

            new_name = os.path.splitext(filename)[0] + ".jpg"
            out_path = os.path.join(folder, new_name)
            cv2.imwrite(out_path, img)
            print(f"Converted: {filename} -> {new_name}")

convert_with_cv2('/content/CVC-ClinicDB/Original')
convert_with_cv2('/content/CVC-ClinicDB/GroundTruth')

from pickle import TRUE
!pip install --upgrade timm
import timm
print("swinv2" in timm.list_models(pretrained=True))  # Check if any swinv2 exists

# List all available Swin V2 models
for m in timm.list_models('swinv2*',pretrained=TRUE):
    print(m)

import os
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, Subset, ConcatDataset
import timm
import numpy as np
import random

# Albumentations for augmentations
import albumentations as A
from albumentations.pytorch import ToTensorV2

# --- MixUp and CutMix for segmentation ---
def mixup_segmentation(images, masks, alpha=0.4):
    '''images: [B, C, H, W], masks: [B, 1, H, W]'''
    lam = np.random.beta(alpha, alpha)
    batch_size = images.size(0)
    index = torch.randperm(batch_size).to(images.device)
    mixed_images = lam * images + (1 - lam) * images[index, :]
    mixed_masks = lam * masks + (1 - lam) * masks[index, :]
    return mixed_images, mixed_masks

def rand_bbox(size, lam):
    W = size[2]
    H = size[3]
    cut_rat = np.sqrt(1. - lam)
    cut_w = np.int32(W * cut_rat)
    cut_h = np.int32(H * cut_rat)
    # uniform
    cx = np.random.randint(W)
    cy = np.random.randint(H)
    bbx1 = np.clip(cx - cut_w // 2, 0, W)
    bby1 = np.clip(cy - cut_h // 2, 0, H)
    bbx2 = np.clip(cx + cut_w // 2, 0, W)
    bby2 = np.clip(cy + cut_h // 2, 0, H)
    return bbx1, bby1, bbx2, bby2

def cutmix_segmentation(images, masks, alpha=0.4):
    '''images: [B, C, H, W], masks: [B, 1, H, W]'''
    lam = np.random.beta(alpha, alpha)
    batch_size = images.size(0)
    index = torch.randperm(batch_size).to(images.device)
    bbx1, bby1, bbx2, bby2 = rand_bbox(images.size(), lam)
    images_cutmix = images.clone()
    masks_cutmix = masks.clone()
    images_cutmix[:, :, bbx1:bbx2, bby1:bby2] = images[index, :, bbx1:bbx2, bby1:bby2]
    masks_cutmix[:, :, bbx1:bbx2, bby1:bby2] = masks[index, :, bbx1:bbx2, bby1:bby2]
    return images_cutmix, masks_cutmix

# 1. Dataset with Albumentations
class KvasirSegDataset(Dataset):
    def __init__(self, images_dir, masks_dir, transform=None, mask_extension='.jpg'):
        self.images_dir = images_dir
        self.masks_dir = masks_dir
        self.transform = transform
        self.mask_extension = mask_extension
        self.images = sorted([f for f in os.listdir(images_dir) if f.lower().endswith(('.jpg','.jpeg','.png'))])

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_name = self.images[idx]
        img_path = os.path.join(self.images_dir, img_name)
        base_name = os.path.splitext(img_name)[0]
        mask_name = base_name + self.mask_extension
        mask_path = os.path.join(self.masks_dir, mask_name)

        image = np.array(Image.open(img_path).convert("RGB"))
        try:
            mask = np.array(Image.open(mask_path).convert("L"))
        except FileNotFoundError:
            raise FileNotFoundError(f"Mask not found: {mask_path}")

        mask = (mask > 0).astype('float32')  # Binarize

        if self.transform:
            augmented = self.transform(image=image, mask=mask)
            image = augmented['image']
            mask = augmented['mask'].unsqueeze(0)  # [1, H, W]
        else:
            image = T.ToTensor()(Image.fromarray(image))
            mask = torch.tensor(mask).unsqueeze(0)

        return image, mask

# 2. Model Blocks (unchanged)
class MDCB(nn.Module):
    def __init__(self, in_ch, out_ch, dilations=[1, 2, 4]):
        super().__init__()
        self.convs = nn.ModuleList([
            nn.Conv2d(in_ch, out_ch, kernel_size=3, padding=d, dilation=d)
            for d in dilations
        ])
        self.relu = nn.ReLU(inplace=True)
        self.fuse = nn.Conv2d(len(dilations)*out_ch, out_ch, kernel_size=1)

    def forward(self, x):
        features = [conv(x) for conv in self.convs]
        x = torch.cat(features, dim=1)
        x = self.fuse(x)
        return self.relu(x)

class MFAB(nn.Module):
    def __init__(self, in_chs, out_ch):
        super().__init__()
        self.conv = nn.Conv2d(sum(in_chs), out_ch, kernel_size=1)

    def forward(self, *features):
        target_size = features[0].shape[2:]
        resized_features = [features[0]]
        for i in range(1, len(features)):
            resized = F.interpolate(features[i], size=target_size, mode='bicubic', align_corners=False)
            resized_features.append(resized)
        x = torch.cat(resized_features, dim=1)
        return self.conv(x)

# 3. SwinE-Net Model (unchanged)
class SwinENet(nn.Module):
    def __init__(self, num_classes=1,
                 swin_backbone='swin_base_patch4_window7_224',
                 effnet_backbone='efficientnet_b3'):
        super().__init__()
        self.swin = timm.create_model(swin_backbone, pretrained=True, features_only=True)
        swin_channels = self.swin.feature_info.channels()
        self.effnet = timm.create_model(effnet_backbone, pretrained=True, features_only=True)
        effnet_channels = self.effnet.feature_info.channels()
        num_stages = min(len(swin_channels), len(effnet_channels))
        swin_channels = swin_channels[:num_stages]
        effnet_channels = effnet_channels[:num_stages]
        self.num_stages = num_stages
        fused_channels = [s+e for s, e in zip(swin_channels, effnet_channels)]
        self.mdcb = nn.ModuleList([MDCB(fused_ch, fused_ch) for fused_ch in fused_channels])
        decoder_in_ch = fused_channels[-1]
        self.decoder = nn.ModuleList([
            nn.ConvTranspose2d(decoder_in_ch, 256, 2, stride=2),
            nn.ConvTranspose2d(256, 128, 2, stride=2),
            nn.ConvTranspose2d(128, 64, 2, stride=2)
        ])
        self.mfab = MFAB([fused_channels[0], fused_channels[1], fused_channels[2]], 64)
        self.final_conv = nn.Conv2d(64, num_classes, 1)

    def forward(self, x):
        swin_feats = self.swin(x)
        effnet_feats = self.effnet(x)
        swin_feats_processed = []
        for f, ch in zip(swin_feats, self.swin.feature_info.channels()[:self.num_stages]):
            if f.ndim == 3:
                B, HW, C = f.shape
                H = W = int(HW**0.5)
                swin_feats_processed.append(f.view(B, H, W, C).permute(0, 3, 1, 2))
            elif f.ndim == 4:
                if f.shape[-1] == ch and f.shape[1] != ch:
                    swin_feats_processed.append(f.permute(0, 3, 1, 2))
                else:
                    swin_feats_processed.append(f)
            else:
                raise ValueError(f"Unexpected Swin feature tensor shape: {f.shape}")
        effnet_feats_processed = []
        for f, ch in zip(effnet_feats, self.effnet.feature_info.channels()[:self.num_stages]):
            if f.ndim == 4:
                if f.shape[-1] == ch and f.shape[1] != ch:
                    effnet_feats_processed.append(f.permute(0, 3, 1, 2))
                else:
                    effnet_feats_processed.append(f)
            else:
                raise ValueError(f"Unexpected EfficientNet feature tensor shape: {f.shape}")
        fused_feats = []
        for swin_f, effnet_f in zip(swin_feats_processed, effnet_feats_processed):
            if swin_f.shape[2:] != effnet_f.shape[2:]:
                target_size = swin_f.shape[2:]
                effnet_f_resized = F.interpolate(effnet_f, size=target_size, mode='bilinear', align_corners=False)
                fused_feats.append(torch.cat([swin_f, effnet_f_resized], dim=1))
            else:
                fused_feats.append(torch.cat([swin_f, effnet_f], dim=1))
        feats = [mdcb(f) for mdcb, f in zip(self.mdcb, fused_feats)]
        x = feats[-1]
        for dec in self.decoder:
            x = dec(x)
        mfab_inputs = [feats[0]]
        if feats[1].shape[2:] != feats[0].shape[2:]:
             resized_feat1 = F.interpolate(feats[1], size=feats[0].shape[2:], mode='bilinear', align_corners=False)
             mfab_inputs.append(resized_feat1)
        else:
             mfab_inputs.append(feats[1])
        if feats[2].shape[2:] != feats[0].shape[2:]:
             resized_feat2 = F.interpolate(feats[2], size=feats[0].shape[2:], mode='bilinear', align_corners=False)
             mfab_inputs.append(resized_feat2)
        else:
             mfab_inputs.append(feats[2])
        x = self.mfab(*mfab_inputs)
        x = self.final_conv(x)
        if x.shape[2:] != (224, 224):
            x = F.interpolate(x, size=(224, 224), mode='bilinear', align_corners=False)
        return x

# 4. Albumentations Transforms
train_transform = A.Compose([
    A.Resize(224, 224),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.RandomRotate90(p=0.5),
    A.Affine(translate_percent=0.1, scale=1.1, rotate=15, p=0.5),
    A.ElasticTransform(alpha=120, sigma=120*0.07, p=0.2),    # removed alpha_affine
    A.RandomBrightnessContrast(p=0.5),
    A.GaussNoise(var_limit=(10, 50), p=0.3),                 # ints, not floats
    A.MotionBlur(blur_limit=5, p=0.2),
    A.GridDistortion(p=0.2),
    A.OpticalDistortion(distort_limit=0.1, p=0.2),           # removed shift_limit
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

val_transform = A.Compose([
    A.Resize(224, 224),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

# 5. Dataset/Dataloader with Albumentations
dataset_kvasir = KvasirSegDataset(
    images_dir='/content/Kvasir-SEG/images',
    masks_dir='/content/Kvasir-SEG/masks',
    transform=train_transform,
    mask_extension='.jpg'
)

dataset_clinicdb = KvasirSegDataset(
    images_dir='/content/CVC-ClinicDB/Original',
    masks_dir='/content/CVC-ClinicDB/GroundTruth',
    transform=train_transform,
    mask_extension='.jpg'
)

dataset = ConcatDataset([dataset_kvasir, dataset_clinicdb])
np.random.seed(42)
dataset_size = len(dataset)
indices = np.arange(dataset_size)
np.random.shuffle(indices)

split = int(0.1 * dataset_size)  # 10% for validation
val_indices = indices[:split]
train_indices = indices[split:]

train_dataset = Subset(dataset, train_indices)
val_dataset = Subset(dataset, val_indices)

# For validation, switch to val_transform
train_dataset.dataset.datasets[0].transform = train_transform
train_dataset.dataset.datasets[1].transform = train_transform
val_dataset.dataset.datasets[0].transform = val_transform
val_dataset.dataset.datasets[1].transform = val_transform

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False)

# 6. Model instantiation
model = SwinENet(num_classes=1)
model.cuda()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-5)

# 7. Loss Function
class BCEIoULoss(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, logits, targets, weight=None, eps=1e-7):
        bce = F.binary_cross_entropy_with_logits(logits, targets, weight=weight)
        probs = torch.sigmoid(logits)
        probs = probs.view(-1)
        targets = targets.view(-1)
        if weight is not None:
            weight = weight.view(-1)
            intersection = (weight * probs * targets).sum()
            union = (weight * (probs + targets - probs * targets)).sum()
        else:
            intersection = (probs * targets).sum()
            union = (probs + targets - probs * targets).sum()
        iou = (intersection + eps) / (union + eps)
        iou_loss = 1 - iou
        return bce + iou_loss

criterion = BCEIoULoss()

# 8. Scheduler
from torch.optim.lr_scheduler import ReduceLROnPlateau
scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5, min_lr=1e-6, verbose=True)

# 9. Training model with weighted loss, scheduler, augmentation, and MixUp/CutMix
num_epochs = 15  # Increase as needed

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    for i, (images, masks) in enumerate(train_loader):
        images = images.cuda()
        masks = masks.cuda()
        # --- Apply MixUp or CutMix ---
        p = random.random()
        if p < 0.5:
            images, masks = mixup_segmentation(images, masks, alpha=0.4)
        else:
            images, masks = cutmix_segmentation(images, masks, alpha=0.4)
        optimizer.zero_grad()
        # Weighted loss: 5 for foreground, 1 for background
        weight_map = torch.ones_like(masks)
        weight_map[masks == 1] = 5.0
        loss = criterion(model(images), masks, weight=weight_map)
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * images.size(0)
    epoch_loss = running_loss / len(train_loader.dataset)
    print(f"Epoch {epoch+1}/{num_epochs}, Train Loss: {epoch_loss:.4f}")

    # --- Validation loop (no MixUp/CutMix) ---
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for images, masks in val_loader:
            images = images.cuda()
            masks = masks.cuda()
            preds = model(images)
            # Validation loss (no weighting, no MixUp/CutMix)
            loss = criterion(preds, masks)
            val_loss += loss.item() * images.size(0)
    val_loss /= len(val_loader.dataset)
    print(f"Epoch {epoch+1}/{num_epochs}, Val Loss: {val_loss:.4f}")

    # Step the scheduler with validation loss
    scheduler.step(val_loss)

print(f"Kvasir images: {len(dataset_kvasir)}")
print(f"ClinicDB images: {len(dataset_clinicdb)}")
print(f"Total images after concatenation: {len(dataset)}")
print(f"Training size: {len(train_dataset)}")
print(f"Validation size: {len(val_dataset)}")

# 8. Saving the model
model_save_path = '/content/swinenet_kvasir_seg.pth'
torch.save(model.state_dict(), model_save_path)
print(f"Model saved to {model_save_path}")

# 9. Save prediction masks
model.eval()
output_masks_dir = '/content/predicted_masks'

os.makedirs(output_masks_dir, exist_ok=True)

total_saved_count = 0

with torch.no_grad():
    for i, (images, masks) in enumerate(val_loader):
        images = images.cuda()
        preds = model(images)

        # Applying sigmoid and threshold to get binary masks
        predicted_masks = torch.sigmoid(preds) > 0.5

        for j in range(images.size(0)):
            mask_img = predicted_masks[j].squeeze(0).byte().cpu() * 255
            mask_pil = Image.fromarray(mask_img.numpy(), mode='L')

            mask_filename = f"predicted_mask_{total_saved_count:04d}.jpg"
            mask_filepath = os.path.join(output_masks_dir, mask_filename)
            mask_pil.save(mask_filepath)
            print(f"Saved predicted mask to {mask_filepath}")

            total_saved_count += 1

print(f"Finished saving {total_saved_count} predicted masks.")

# 10. Printing predictions

import torchmetrics
from torchmetrics.segmentation import DiceScore

try:
    model
except NameError:
    print("Model not found, instantiating SwinENet.")
    model = SwinENet(num_classes=1)

model_save_path = '/content/swinenet_kvasir_seg.pth'
if os.path.exists(model_save_path):
    try:
        model.load_state_dict(torch.load(model_save_path))
        print(f"Loaded model from {model_save_path}")
    except RuntimeError as e:
        print(f"Error loading model state_dict: {e}")
        print("This might happen if the model architecture definition has changed or device mismatch.")
else:
    print(f"Model state dict not found at {model_save_path}. Cannot evaluate.")

model.cuda()

model.eval()

# Move metric objects to the GPU
metric_iou = torchmetrics.JaccardIndex(task="binary").cuda()
metric_dice = DiceScore(num_classes=2).cuda()
metric_accuracy = torchmetrics.Accuracy(task="binary").cuda()


print("\nCalculating evaluation metrics...")

with torch.no_grad():
      try:
        val_loader
      except NameError:
          print("Validation DataLoader not found. Please run the cell that defines the val_loader.")
          exit()

      for i, (images, masks) in enumerate(val_loader):

        images = images.cuda()
        masks = masks.cuda()

        preds = model(images)

        print(f"Batch {i}:")
        print(f"  Raw predictions shape: {preds.shape}")
        print(f"  Raw predictions min: {preds.min().item()}, max: {preds.max().item()}")
        sigmoid_preds = torch.sigmoid(preds)
        print(f"  Sigmoid predictions min: {sigmoid_preds.min().item()}, max: {sigmoid_preds.max().item()}")


        predicted_masks_binary = (torch.sigmoid(preds) > 0.5).int()  # Convert to binary masks
        masks_binary = (masks > 0).int()

        # Pass GPU tensors to the GPU metric objects
        metric_iou.update(predicted_masks_binary, masks_binary)
        metric_dice.update(predicted_masks_binary, masks_binary)
        metric_accuracy.update(predicted_masks_binary, masks_binary)

final_iou = metric_iou.compute()
final_dice = metric_dice.compute()
final_accuracy = metric_accuracy.compute()

print(f"Evaluation Metrics over the entire Kvasir & ClinicDB dataset:")
print(f"  Mean IoU: {final_iou.item():.4f}")
print(f"  Mean Dice: {final_dice.item():.4f}")
print(f"  Overall Accuracy: {final_accuracy.item():.4f}")

metric_iou.reset()
metric_dice.reset()
metric_accuracy.reset()

!zip -r /content/predicted_masks.zip /content/predicted_masks

from google.colab import files
files.download("/content/predicted_masks.zip")

num_kvasir = len(dataset_kvasir)
num_clinicdb = len(dataset_clinicdb)

# val_indices is a list of indices in the combined ConcatDataset
val_indices_kvasir = [idx for idx in val_indices if idx < num_kvasir]

kvasir_val_dataset = Subset(dataset_kvasir, val_indices_kvasir)
kvasir_val_loader = DataLoader(kvasir_val_dataset, batch_size=8, shuffle=False)

# --- Kvasir-only Validation loop ---
model.eval()
kvasir_val_loss = 0.0
with torch.no_grad():
    for images, masks in kvasir_val_loader:
        images = images.cuda()
        masks = masks.cuda()
        preds = model(images)
        loss = criterion(preds, masks)
        kvasir_val_loss += loss.item() * images.size(0)
kvasir_val_loss /= len(kvasir_val_loader.dataset)
print(f"Epoch {epoch+1}/{num_epochs}, Kvasir Val Loss: {kvasir_val_loss:.4f}")

import torch
import numpy as np

def dice_coefficient(preds, targets, eps=1e-7):
    # preds, targets: [N, H, W] or [N, 1, H, W]
    preds = preds.reshape(-1)
    targets = targets.reshape(-1)
    intersection = (preds * targets).sum()
    return (2. * intersection + eps) / (preds.sum() + targets.sum() + eps)

def iou_score(preds, targets, eps=1e-7):
    # preds, targets: [N, H, W] or [N, 1, H, W]
    preds = preds.reshape(-1)
    targets = targets.reshape(-1)
    intersection = (preds * targets).sum()
    union = preds.sum() + targets.sum() - intersection
    return (intersection + eps) / (union + eps)

def pixel_accuracy(preds, targets):
    # preds, targets: [N, H, W] or [N, 1, H, W]
    preds = preds.reshape(-1)
    targets = targets.reshape(-1)
    return (preds == targets).sum().item() / preds.numel()

# --- Evaluate on Kvasir val set ---
model.eval()
dice_total = 0.0
iou_total = 0.0
acc_total = 0.0
n_batches = 0

with torch.no_grad():
    for images, masks in kvasir_val_loader:
        images = images.cuda()
        masks = masks.cuda()
        logits = model(images)
        probs = torch.sigmoid(logits)
        preds = (probs > 0.5).float()
        # Remove channel dim if present
        if preds.ndim == 4:
            preds = preds[:, 0]
            masks = masks[:, 0]
        dice = dice_coefficient(preds.cpu(), masks.cpu())
        iou = iou_score(preds.cpu(), masks.cpu())
        acc = pixel_accuracy(preds.cpu(), masks.cpu())
        dice_total += dice
        iou_total += iou
        acc_total += acc
        n_batches += 1

print(f"Kvasir Validation Metrics:")
print(f"Mean Dice: {dice_total / n_batches:.4f}")
print(f"Mean IoU: {iou_total / n_batches:.4f}")
print(f"Mean Accuracy: {acc_total / n_batches:.4f}")

import torch
import numpy as np

def dice_coefficient(preds, targets, eps=1e-7):
    preds = preds.reshape(-1)
    targets = targets.reshape(-1)
    intersection = (preds * targets).sum()
    return (2. * intersection + eps) / (preds.sum() + targets.sum() + eps)

def iou_score(preds, targets, eps=1e-7):
    preds = preds.reshape(-1)
    targets = targets.reshape(-1)
    intersection = (preds * targets).sum()
    union = preds.sum() + targets.sum() - intersection
    return (intersection + eps) / (union + eps)

def pixel_accuracy(preds, targets):
    preds = preds.reshape(-1)
    targets = targets.reshape(-1)
    return (preds == targets).sum().item() / preds.numel()

# --- Prepare ClinicDB-only val loader ---
num_kvasir = len(dataset_kvasir)
num_clinicdb = len(dataset_clinicdb)
val_indices_clinicdb = [idx - num_kvasir for idx in val_indices if idx >= num_kvasir]
clinicdb_val_dataset = Subset(dataset_clinicdb, val_indices_clinicdb)
clinicdb_val_loader = DataLoader(clinicdb_val_dataset, batch_size=8, shuffle=False)

# --- Evaluate on ClinicDB val set ---
model.eval()
dice_total = 0.0
iou_total = 0.0
acc_total = 0.0
n_batches = 0

with torch.no_grad():
    for images, masks in clinicdb_val_loader:
        images = images.cuda()
        masks = masks.cuda()
        logits = model(images)
        probs = torch.sigmoid(logits)
        preds = (probs > 0.5).float()
        if preds.ndim == 4:
            preds = preds[:, 0]
            masks = masks[:, 0]
        dice = dice_coefficient(preds.cpu(), masks.cpu())
        iou = iou_score(preds.cpu(), masks.cpu())
        acc = pixel_accuracy(preds.cpu(), masks.cpu())
        dice_total += dice
        iou_total += iou
        acc_total += acc
        n_batches += 1

print(f"ClinicDB Validation Metrics:")
print(f"Mean Dice: {dice_total / n_batches:.4f}")
print(f"Mean IoU: {iou_total / n_batches:.4f}")
print(f"Mean Accuracy: {acc_total / n_batches:.4f}")